const intents = [
  { id:"resumo_heloisa", keywords:["resume","resuma","fale mais","tell me more","conta o que","preciso saber","need to know","quem e ela","who is she","me conta","resumo","summary","overview","geral","general","tudo sobre","all about","conta sobre ela","sobre ela"],
    pt:"A Helo\u00edsa \u00e9 estudante de Ci\u00eancia da Computa\u00e7\u00e3o pela Est\u00e1cio, com experi\u00eancia em suporte t\u00e9cnico na Zapier e atendimento no F\u00f3rum Florian\u00f3polis. Atualmente focada em Quality Assurance, testes manuais, APIs e Postman.",
    en:"Helo\u00edsa is a Computer Science student at Est\u00e1cio, with experience in technical support at Zapier and customer service at F\u00f3rum Florian\u00f3polis. Currently focused on Quality Assurance, manual testing, APIs, and Postman.",
    page:"resumo", pageLabelPt:"Ver Curr\u00edculo", pageLabelEn:"See Resume" },
  { id:"quem", keywords:["quem","quem e","who","who is","fale sobre","tell me about","me fala","descreve","describe","apresent","essa","this person"],
    pt:"Helo\u00edsa Dresch, estudante de Ci\u00eancia da Computa\u00e7\u00e3o, buscando sua primeira oportunidade como Junior QA Analyst. Foco em testes manuais, API testing e Postman!",
    en:"Helo\u00edsa Dresch, Computer Science student, seeking her first opportunity as a Junior QA Analyst. Focus on manual testing, API testing, and Postman!" },
  { id:"nome", keywords:["nome completo","full name","nome dela","her name","nome todo","sobrenome","last name","primeiro nome","first name","como ela se chama","what is her name","dresch","heloisa"],
    pt:"Helo\u00edsa Dresch!",
    en:"Helo\u00edsa Dresch!" },
  { id:"objetivo", keywords:["objetivo","goal","sonho","dream","futuro","future","plano","plan","quer ser","wants to be","pretende","intends","ambicao","ambition","meta"],
    pt:"Conquistar sua primeira oportunidade como Junior QA Analyst e se desenvolver na \u00e1rea de Quality Assurance!",
    en:"Land her first opportunity as a Junior QA Analyst and grow in the Quality Assurance field!" },
  { id:"nivel_exp", keywords:["nivel de experiencia","experience level","junior","pleno","senior","senioridade","seniority","qual nivel","what level","jr","mid","sr"],
    pt:"Junior! Ela est\u00e1 em in\u00edcio de carreira na \u00e1rea de QA, com base s\u00f3lida em suporte t\u00e9cnico e atendimento.",
    en:"Junior! She's starting her QA career with a solid foundation in technical support and customer service." },
  { id:"qa", keywords:["qa","quality assurance","qualidade","quality","teste","test","testing","testes","validacao","validation"],
    pt:"QA \u00e9 o foco! Testes manuais, funcionais, regress\u00e3o, API testing com Postman, documenta\u00e7\u00e3o de bugs e cria\u00e7\u00e3o de test cases!",
    en:"QA is her focus! Manual testing, functional testing, regression, API testing with Postman, bug documentation, and test case creation!" },
  { id:"api", keywords:["api","postman","endpoint","rest","restful","requisicao","request","json","webhook"],
    pt:"API Testing \u00e9 com ela! Postman, valida\u00e7\u00e3o de endpoints REST, status codes e respostas JSON!",
    en:"API Testing is her thing! Postman, REST endpoint validation, status codes, and JSON responses!" },
  { id:"bug", keywords:["bug","bugs","defeito","defect","erro","error","falha","failure","problema","problem","report","relatorio"],
    pt:"Documenta\u00e7\u00e3o de bugs com passos de reprodu\u00e7\u00e3o, evid\u00eancias e classifica\u00e7\u00e3o de severidade!",
    en:"Bug documentation with reproduction steps, evidence, and severity classification!" },
  { id:"experiencia", keywords:["experiencia","experience","quanto tempo","how long","trabalha ha","carreira","career","trajetoria","trajectory"],
    pt:"Experi\u00eancia em suporte t\u00e9cnico na Zapier (2025-2026) e atendimento no F\u00f3rum Florian\u00f3polis (2023). Agora focada em QA!",
    en:"Experience in technical support at Zapier (2025-2026) and customer service at F\u00f3rum Florian\u00f3polis (2023). Now focused on QA!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"zapier", keywords:["zapier","suporte tecnico","technical support","integracao","integration","automacao","automation"],
    pt:"Na Zapier (2025-2026): suporte t\u00e9cnico remoto, an\u00e1lise de erros em integra\u00e7\u00f5es, valida\u00e7\u00e3o de fluxos, APIs e troubleshooting t\u00e9cnico!",
    en:"At Zapier (2025-2026): remote technical support, integration error analysis, workflow validation, APIs, and technical troubleshooting!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"forum", keywords:["forum","florianopolis","atendimento","customer service","analista de atendimento"],
    pt:"No F\u00f3rum Florian\u00f3polis (2023): atendimento presencial, webchat, e-mail e telefone, organiza\u00e7\u00e3o de demandas e suporte a usu\u00e1rios!",
    en:"At F\u00f3rum Florian\u00f3polis (2023): in-person, webchat, email, and phone service, demand organization, and user support!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"formacao", keywords:["formado","formou","graduado","graduacao","faculdade","universidade","university","college","estudou","estudo","education","graduated","degree","diploma","curso superior","ensino superior","ciencia da computacao","computer science","estacio","formacao","onde estudou"],
    pt:"Cursando Ci\u00eancia da Computa\u00e7\u00e3o pela Est\u00e1cio (2025 - atualmente)!",
    en:"Studying Computer Science at Est\u00e1cio (2025 - present)!",
    page:"resumo", pageLabelPt:"Ver Forma\u00e7\u00e3o", pageLabelEn:"See Education" },
  { id:"certificados", keywords:["certificado","certificacao","certificados","certification","certified","curso","cursos","courses","treinamento","training","qualificacao","ebac"],
    pt:"Certifica\u00e7\u00f5es em andamento: QA Fundamentals, API Testing Fundamentals e Postman for QA! Al\u00e9m do curso de TI na EBAC.",
    en:"Certifications in progress: QA Fundamentals, API Testing Fundamentals, and Postman for QA! Plus the IT program at EBAC.",
    page:"resumo", pageLabelPt:"Ver Cursos", pageLabelEn:"See Courses" },
  { id:"habilidades", keywords:["habilidade","habilidades","skill","skills","sabe fazer","can do","competencia","o que ela faz","what does she do","faz o que","trabalha com","works with","domina","master","tecnologia","tech"],
    pt:"Quality Assurance, Manual Testing, API Testing, Postman, Bug Reporting, Test Cases, Functional Testing, Regression Testing, REST APIs, JSON, Jira, Scrum/Agile, Troubleshooting, Chrome DevTools, Linux e HTTP/HTTPS!",
    en:"Quality Assurance, Manual Testing, API Testing, Postman, Bug Reporting, Test Cases, Functional Testing, Regression Testing, REST APIs, JSON, Jira, Scrum/Agile, Troubleshooting, Chrome DevTools, Linux, and HTTP/HTTPS!" },
  { id:"ferramentas", keywords:["ferramenta","ferramentas","tool","tools","usa","uses","programa","programs","software"],
    pt:"Postman, Jira, Swagger, Chrome DevTools, Wireshark, Zendesk, Movidesk e Trello!",
    en:"Postman, Jira, Swagger, Chrome DevTools, Wireshark, Zendesk, Movidesk, and Trello!" },
  { id:"projetos", keywords:["projeto","project","projetos","projects","portfolio","portf\u00f3lio"],
    pt:"Dois projetos QA: API Testing with Postman (valida\u00e7\u00e3o de APIs REST) e E-commerce Website Testing (cen\u00e1rios de teste para login e checkout)!",
    en:"Two QA projects: API Testing with Postman (REST API validation) and E-commerce Website Testing (test scenarios for login and checkout)!",
    page:"resumo", pageLabelPt:"Ver Projetos", pageLabelEn:"See Projects" },
  { id:"diferencial", keywords:["diferencial","differenti","destaca","stand out","por que contratar","why hire","ponto forte","strength","qualidade","quality","melhor","best"],
    pt:"O diferencial? Aten\u00e7\u00e3o aos detalhes, aprendizado r\u00e1pido, experi\u00eancia real com APIs e suporte t\u00e9cnico, e muita vontade de crescer em QA!",
    en:"Her edge? Attention to detail, quick learning, real experience with APIs and technical support, and strong drive to grow in QA!" },
  { id:"disponibilidade", keywords:["disponibilidade","availability","quando pode","when can","comecar","start","inicio","begin","imediato","immediate","pronto","ready"],
    pt:"Ela est\u00e1 dispon\u00edvel para novas oportunidades! Melhor combinar direto com ela no WhatsApp.",
    en:"She's available for new opportunities! Best to arrange directly via WhatsApp.",
    page:"contato", pageLabelPt:"Ver Contato", pageLabelEn:"See Contact" },
  { id:"pretensao", keywords:["pretensao","salary","salario","remuneracao","compensation","quanto ganha","how much","quanto quer","paga","pay","valor"],
    pt:"Essa \u00e9 confidencial! Melhor alinhar direto com ela no WhatsApp.",
    en:"That's confidential! Best to discuss directly via WhatsApp.",
    page:"contato", pageLabelPt:"Falar com Helo\u00edsa", pageLabelEn:"Talk to Helo\u00edsa" },
  { id:"contato", keywords:["contato","contact","falar com","talk to","chamar","ligar","call","email","telefone","phone","whatsapp","wpp","zap","numero","number","linkedin","github"],
    pt:"WhatsApp \u00e9 o mais r\u00e1pido! Tamb\u00e9m est\u00e1 no LinkedIn e GitHub.",
    en:"WhatsApp is fastest! Also on LinkedIn and GitHub.",
    page:"contato", pageLabelPt:"Ver Contato", pageLabelEn:"See Contact" },
  { id:"localizacao", keywords:["mora","morar","live","lives","cidade","city","estado","state","pais","country","brasil","brazil","santa catarina","sc","regiao","region","local","location","endereco","address"],
    pt:"Santa Catarina, Brasil!",
    en:"Santa Catarina, Brazil!",
    page:"contato", pageLabelPt:"Ver no Mapa", pageLabelEn:"See on Map" },
  { id:"idiomas", keywords:["idioma","lingua","language","ingles","english","fala","speak","portugues","portuguese","bilingue","bilingual","fluente","fluent"],
    pt:"Portugu\u00eas nativo e conhecimento em Ingl\u00eas!",
    en:"Native Portuguese and English knowledge!" },
  { id:"servicos", keywords:["servico","servicos","service","services","oferece","offer","atende","area","atuacao"],
    pt:"Quality Assurance (testes manuais, funcionais e regress\u00e3o) e API Testing (valida\u00e7\u00e3o com Postman)!",
    en:"Quality Assurance (manual, functional, and regression testing) and API Testing (Postman validation)!" },
  { id:"curriculo", keywords:["curriculo","cv","baixar","download","pdf","documento","document"],
    pt:"Dispon\u00edvel ali em cima, bot\u00e3o 'Baixar Curr\u00edculo'!",
    en:"Available above, 'Download Resume' button!" },
  { id:"troubleshooting", keywords:["troubleshooting","diagnostico","diagnosis","resolver problema","solve problem","debug","depurar","investigar","investigate","root cause","causa raiz"],
    pt:"Troubleshooting adquirido na Zapier! An\u00e1lise de erros, valida\u00e7\u00e3o de fluxos e investiga\u00e7\u00e3o de problemas em integra\u00e7\u00f5es!",
    en:"Troubleshooting acquired at Zapier! Error analysis, workflow validation, and integration issue investigation!" },
  { id:"jira", keywords:["jira","scrum","agile","kanban","sprint","metodologia","methodology"],
    pt:"Conhecimento em Jira para gest\u00e3o de bugs e tarefas, e metodologias \u00e1geis como Scrum!",
    en:"Knowledge of Jira for bug and task management, and agile methodologies like Scrum!" },
  { id:"contratar", keywords:["contratar","contrat","hire","hiring","emprego","job","vaga","vacancy","disponivel","available","recrutamento","recruiting","freelancer","freelance","proposta","proposal"],
    pt:"Quer contratar? Dedicada, atenciosa e com sede de aprender. Chama no WhatsApp!",
    en:"Want to hire? Dedicated, detail-oriented, and eager to learn. Reach out via WhatsApp!",
    page:"contato", pageLabelPt:"Ver Contato", pageLabelEn:"See Contact" },
  { id:"ia", keywords:["voce","quem e voce","who are you","e voce","are you","robo","robot","ia","inteligencia artificial","artificial intelligence","chatbot","bot","assistente","assistant"],
    pt:"Sou a Assistente da Helo\u00edsa. Sem f\u00e9rias, sem 13\u00ba... mas adoro contar sobre ela!",
    en:"I'm Helo\u00edsa's Assistant. No vacation, no bonuses... but I love talking about her!" },
  { id:"elogio", keywords:["legal","cool","bonito","beautiful","incrivel","amazing","show","parabens","top","demais","awesome","massa","nice","lindo","wow"],
    pt:"Vou contar pra ela! Brincadeira... ou n\u00e3o!",
    en:"I'll tell her! Just kidding... or not!" },
  { id:"bom", keywords:["bom","good","great","otimo","excelente","excellent","vale a pena","worth","recomend","recommend","presta","confia","trust","confiar"],
    pt:"Se ela \u00e9 boa? Na minha opini\u00e3o ela \u00e9 \u00f3tima no que faz! Pode confiar.",
    en:"Is she good? In my opinion, she's great at what she does!" }
];
